"""
Warm pool of companion selfies, generated by HeyGen.

HeyGen look generation is asynchronous (tens of seconds) and billed per look, so
we generate ahead into a pool instead of generating per request:

  top_up_pool()  - background job. Finds scenes that are thin and asks HeyGen
                   to generate looks for them.
  sync_pool()    - background job. Mirrors finished looks into Supabase Storage
                   and marks them ready.

The request path then just picks a ready image - instant, free, and always the
companion's real face because every image came from her trained HeyGen LoRA.

Bucket: companion-selfies (public)   Table: companion_selfies
Run scripts/selfie_pool_migration.sql once before using this.
"""
from __future__ import annotations

import logging
import os
import uuid

import httpx

from app import heygen_client

logger = logging.getLogger(__name__)

_BUCKET = "companion-selfies"
_TABLE = "companion_selfies"

_TARGET_PER_SCENE = 3
# Hard ceiling per run so a misconfiguration cannot burn a month of HeyGen credits.
_MAX_GENERATIONS_PER_RUN = 6

SCENES: list[dict] = [
    {
        "scene": "cafe",
        "tags": ["cafe", "coffee", "morning", "breakfast", "out", "casual"],
        "prompt": "sitting in a warm sunlit cafe, casual knit sweater, holding a coffee cup, "
                  "soft natural window light, relaxed candid smile, phone selfie framing",
        "pose": "close_up",
    },
    {
        "scene": "home_evening",
        "tags": ["home", "evening", "night", "cozy", "tired", "bed", "relaxing"],
        "prompt": "at home in the evening, soft warm lamplight, comfortable oversized sweatshirt, "
                  "hair down and relaxed, cozy living room background, gentle candid expression",
        "pose": "close_up",
    },
    {
        "scene": "outdoors_walk",
        "tags": ["walk", "outside", "park", "outdoors", "fresh", "air", "sunny", "weather"],
        "prompt": "outdoors on a walk in a green park, light jacket, natural daylight, "
                  "wind in hair, cheerful candid expression, phone selfie framing",
        "pose": "half_body",
    },
    {
        "scene": "workout",
        "tags": ["gym", "workout", "run", "exercise", "training", "fitness"],
        "prompt": "at the gym after a workout, athletic top, hair tied back, slight flush, "
                  "bright gym lighting, energetic candid smile, mirror selfie framing",
        "pose": "half_body",
    },
    {
        "scene": "travel",
        "tags": ["travel", "trip", "city", "vacation", "away", "airport", "street"],
        "prompt": "travelling in a city street, stylish coat, golden hour light, "
                  "blurred city background, excited candid expression, phone selfie framing",
        "pose": "half_body",
    },
    {
        "scene": "night_out",
        "tags": ["dinner", "out", "night", "dressed", "party", "drinks", "celebrating"],
        "prompt": "dressed up for an evening out, elegant top, soft restaurant lighting, "
                  "polished styling, warm confident smile, phone selfie framing",
        "pose": "close_up",
    },
]


def _url() -> str:
    return os.environ.get("SUPABASE_URL", "").rstrip("/")


def _headers(prefer: str = "return=representation") -> dict[str, str]:
    key = os.environ.get("SUPABASE_SERVICE_KEY", "")
    return {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
        "Prefer": prefer,
    }


def _configured() -> bool:
    return bool(_url() and os.environ.get("SUPABASE_SERVICE_KEY"))


async def _rows(companion_id: str | None = None, status: str | None = None) -> list[dict]:
    params = {"select": "*"}
    if companion_id:
        params["companion_id"] = f"eq.{companion_id}"
    if status:
        params["status"] = f"eq.{status}"
    async with httpx.AsyncClient(timeout=10.0) as client:
        resp = await client.get(f"{_url()}/rest/v1/{_TABLE}", headers=_headers(), params=params)
    if resp.status_code != 200:
        logger.error("selfie_pool: row fetch failed (%s): %s", resp.status_code, resp.text[:200])
        return []
    return resp.json() or []


async def _insert(row: dict) -> None:
    async with httpx.AsyncClient(timeout=10.0) as client:
        resp = await client.post(
            f"{_url()}/rest/v1/{_TABLE}", headers=_headers("return=minimal"), json=row
        )
    if resp.status_code not in (200, 201, 204):
        logger.error("selfie_pool: insert failed (%s): %s", resp.status_code, resp.text[:200])


async def _update(row_id: str, patch: dict) -> None:
    async with httpx.AsyncClient(timeout=10.0) as client:
        resp = await client.patch(
            f"{_url()}/rest/v1/{_TABLE}",
            headers=_headers("return=minimal"),
            params={"id": f"eq.{row_id}"},
            json=patch,
        )
    if resp.status_code not in (200, 204):
        logger.error("selfie_pool: update failed (%s): %s", resp.status_code, resp.text[:200])


async def _upload(path: str, data: bytes) -> bool:
    key = os.environ.get("SUPABASE_SERVICE_KEY", "")
    async with httpx.AsyncClient(timeout=30.0) as client:
        resp = await client.post(
            f"{_url()}/storage/v1/object/{_BUCKET}/{path}",
            headers={
                "apikey": key,
                "Authorization": f"Bearer {key}",
                "Content-Type": "image/jpeg",
                "x-upsert": "true",
            },
            content=data,
        )
    if resp.status_code not in (200, 201):
        logger.error("selfie_pool: upload failed (%s): %s", resp.status_code, resp.text[:200])
        return False
    return True


def public_url(storage_path: str) -> str:
    return f"{_url()}/storage/v1/object/public/{_BUCKET}/{storage_path}"


async def top_up_pool() -> None:
    """Ask HeyGen to generate looks for any scene running thin."""
    if not _configured() or not os.environ.get("HEYGEN_API_KEY"):
        logger.info("selfie_pool: top_up skipped - Supabase or HEYGEN_API_KEY not configured")
        return

    started = 0
    for companion_id in ("companion-aeva", "companion-ben"):
        group_id = heygen_client.group_for(companion_id)
        if not group_id:
            logger.info("selfie_pool: no HeyGen group configured for %s - skipping", companion_id)
            continue

        rows = await _rows(companion_id=companion_id)
        counts: dict[str, int] = {}
        for r in rows:
            if r.get("status") != "failed":
                counts[r.get("scene", "")] = counts.get(r.get("scene", ""), 0) + 1

        for spec in SCENES:
            if started >= _MAX_GENERATIONS_PER_RUN:
                logger.info("selfie_pool: hit per-run cap (%s)", _MAX_GENERATIONS_PER_RUN)
                return
            have = counts.get(spec["scene"], 0)
            if have >= _TARGET_PER_SCENE:
                continue
            try:
                gen_id = await heygen_client.generate_look(
                    group_id,
                    spec["prompt"],
                    orientation="vertical",
                    pose=spec.get("pose", "close_up"),
                    style="Realistic",
                )
            except Exception as exc:
                logger.error("selfie_pool: generate failed %s/%s: %r", companion_id, spec["scene"], exc)
                continue

            await _insert({
                "companion_id": companion_id,
                "scene": spec["scene"],
                "tags": spec["tags"],
                "heygen_look_id": gen_id or None,
                "status": "pending",
            })
            started += 1
            logger.info("selfie_pool: queued %s/%s (have %s/%s)",
                        companion_id, spec["scene"], have, _TARGET_PER_SCENE)

    logger.info("selfie_pool: top_up finished - %s generation(s) started", started)


async def sync_pool() -> None:
    """Import any new looks from HeyGen into the pool.

    DISCOVERY-BASED, not generation-based. Looks are created by a human in the
    HeyGen UI ("Design with AI"), which bills against the web subscription. The
    v2 look/generate + train endpoints require separate paid 'api' credits which
    we deliberately do not depend on.

    Mirroring is REQUIRED: HeyGen image_urls are signed and carry an Expires
    param, so linking to them directly would 403 within days.

    SCENE TAGGING: a look is tagged from its NAME in HeyGen. Name looks with
    scene words and they match the right moments, e.g. "Aeva cafe morning".
    """
    if not _configured() or not os.environ.get("HEYGEN_API_KEY"):
        logger.info("selfie_pool: sync skipped - Supabase or HEYGEN_API_KEY not configured")
        return

    known_tags: set[str] = set()
    for spec in SCENES:
        known_tags.update(t.lower() for t in spec["tags"])

    for companion_id in ("companion-aeva", "companion-ben"):
        group_id = heygen_client.group_for(companion_id)
        if not group_id:
            continue

        try:
            looks = await heygen_client.list_group_looks(group_id)
        except Exception as exc:
            logger.error("selfie_pool: list looks failed for %s: %r", companion_id, exc)
            continue

        existing = {r.get("heygen_look_id") for r in await _rows(companion_id=companion_id)}

        imported = 0
        for look in looks:
            look_id = str(look.get("id") or "")
            if not look_id or look_id in existing:
                continue
            if not heygen_client.look_is_ready(look):
                continue
            img_url = heygen_client.look_image_url(look)
            if not img_url:
                continue

            name = str(look.get("name") or "")
            words = {w.strip(".,-_").lower() for w in name.replace("_", " ").replace("-", " ").split()}
            tags = sorted(words & known_tags)
            scene = tags[0] if tags else "generic"

            try:
                async with httpx.AsyncClient(timeout=30.0) as client:
                    img = await client.get(img_url)
                if img.status_code != 200:
                    raise RuntimeError(f"image fetch {img.status_code}")
                path = f"{companion_id}/{scene}-{uuid.uuid4().hex[:8]}.jpg"
                if not await _upload(path, img.content):
                    raise RuntimeError("upload failed")
            except Exception as exc:
                logger.error("selfie_pool: mirror failed for look %s: %r", look_id, exc)
                continue

            await _insert({
                "companion_id": companion_id,
                "scene": scene,
                "tags": tags or [],
                "heygen_look_id": look_id,
                "storage_path": path,
                "status": "ready",
            })
            imported += 1
            logger.info("selfie_pool: imported %s look %r -> %s (tags=%s)",
                        companion_id, name or look_id, path, tags or "none")

        if imported:
            logger.info("selfie_pool: %s - imported %s new look(s)", companion_id, imported)


async def ready_for(companion_id: str) -> list[dict]:
    """All ready pool entries for a companion."""
    if not _configured():
        return []
    return [r for r in await _rows(companion_id=companion_id, status="ready") if r.get("storage_path")]
